### PR TITLE
Fd 594 login dropdown and choosing browser

### PR DESCRIPTION
**Pull request by tanujgupta**
login dropdown and choosing browser

### CODE REVIEW

**Comment by michaellee8** [comment]
@tanujgupta I am not sure if it is a good idea to alter the api to have all login options contained in one class, since Kotlin has optional params anyway, changing the APIs like this would have made it a major release and requires clients to take their effort to match the new API. Also, do you think that we should allow not specifying a provider (i.e. null) to redirect the user to the default login screen? In the swift API I implemented that and it allows the user to select their desired provider instead of specified ones.

**Comment by tanujgupta** [comment]
> @tanujgupta I am not sure if it is a good idea to alter the api to have all login options contained in one class, since Kotlin has optional params anyway, changing the APIs like this would have made it a major release and requires clients to take their effort to match the new API. Also, do you think that we should allow not specifying a provider (i.e. null) to redirect the user to the default login screen? In the swift API I implemented that and it allows the user to select their desired provider instead of specified ones.

@michaellee8 I changed the API to have all the login options contained in one class to match what we have on the web(OpenLoginOptions class). This was done as per discussion with Chai. I think specifying a provider is necessary as those are the only ones we support. No need to redirect to the default login screen.

**Comment by michaellee8** [comment]
> > @tanujgupta I am not sure if it is a good idea to alter the api to have all login options contained in one class, since Kotlin has optional params anyway, changing the APIs like this would have made it a major release and requires clients to take their effort to match the new API. Also, do you think that we should allow not specifying a provider (i.e. null) to redirect the user to the default login screen? In the swift API I implemented that and it allows the user to select their desired provider instead of specified ones.
> 
> @michaellee8 I changed the API to have all the login options contained in one class to match what we have on the web(OpenLoginOptions class). Also, all the params are optional/nullable. This was done as per discussion with Chai. I think specifying a provider is necessary as those are the only ones we support. No need to redirect to the default login screen.

I can see the point of the options changes, I will implement the api changes in the swift sdk then.

However, regarding the unspecified provider support, I think that allowing the client to use the default openlogin screen will allow them to only implement login buttons for some major options like Apple, Google and Facebook, and then provide a Sign in via OpenLogin button to allows users to login with less commonly used providers. Since the openlogin-sdk-frontend already exposes this functionality, I believe it won't do any damage to allow the client to invoke the default login screen by not specifying a login provider.

**Review by chaitanyapotti — APPROVED** [review]
lgtm. good

**Pull request merged**
